# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/stage_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from flask import Blueprint



from PyQt5 import QtCore, QtGui, QtWidgets
stages_bp = Blueprint('stages', __name__)

class Ui_StageForm(object):
    def setupUi(self, StageForm):
        StageForm.setObjectName("StageForm")
        StageForm.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(StageForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stageTitleLabel = QtWidgets.QLabel(StageForm)
        self.stageTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stageTitleLabel.setStyleSheet("font-size: 16pt; font-weight: bold;")
        self.stageTitleLabel.setObjectName("stageTitleLabel")
        self.verticalLayout.addWidget(self.stageTitleLabel)
        self.deadlineLabel = QtWidgets.QLabel(StageForm)
        self.deadlineLabel.setObjectName("deadlineLabel")
        self.verticalLayout.addWidget(self.deadlineLabel)
        self.tableWidget = QtWidgets.QTableWidget(StageForm)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.sendButton = QtWidgets.QPushButton(StageForm)
        self.sendButton.setObjectName("sendButton")
        self.buttonLayout.addWidget(self.sendButton)
        self.attachButton = QtWidgets.QPushButton(StageForm)
        self.attachButton.setObjectName("attachButton")
        self.buttonLayout.addWidget(self.attachButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(StageForm)
        QtCore.QMetaObject.connectSlotsByName(StageForm)

    def retranslateUi(self, StageForm):
        _translate = QtCore.QCoreApplication.translate
        StageForm.setWindowTitle(_translate("StageForm", "Этап"))
        self.stageTitleLabel.setText(_translate("StageForm", "Название этапа"))
        self.deadlineLabel.setText(_translate("StageForm", "Срок: не установлен"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("StageForm", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("StageForm", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("StageForm", "Должность"))
        self.sendButton.setText(_translate("StageForm", "Отправить"))
        self.attachButton.setText(_translate("StageForm", "Прикрепить файл"))
